fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: kampened@gmail.com
        sender_name: Admin
    service:
        mailer: 'fos_user.mailer.twig_swift' # Works as well
    registration:
        confirmation:
            enabled: true